# Generated by Django 4.2.2 on 2023-06-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='body_type',
            field=models.CharField(default=1, max_length=50, verbose_name='Модель кузова'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carlist',
            name='power',
            field=models.CharField(default=1, max_length=50, verbose_name='Мощность двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carlist',
            name='transmission',
            field=models.CharField(default=1, max_length=50, verbose_name='Коробка передач'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carlist',
            name='volume',
            field=models.CharField(default=1, max_length=50, verbose_name='Объем двигателя'),
            preserve_default=False,
        ),
    ]
