# Generated by Django 4.2.2 on 2023-06-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto', '0002_carlist_body_type_carlist_power_carlist_transmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='power',
        ),
        migrations.RemoveField(
            model_name='carlist',
            name='transmission',
        ),
    ]
