# Generated by Django 4.2.2 on 2023-06-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArendaCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20, verbose_name='Марка машины')),
                ('model', models.CharField(max_length=20, verbose_name='Модель машины')),
                ('prce', models.CharField(max_length=20, verbose_name='Цена аренды авто')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Список авто для арены с Avito',
            },
        ),
    ]
