# Generated by Django 4.2.2 on 2023-06-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_avito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arendacar',
            old_name='prce',
            new_name='price',
        ),
    ]
