# Generated by Django 4.2.2 on 2023-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_avito', '0002_rename_prce_arendacar_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='arendacar',
            name='link',
            field=models.CharField(default='', max_length=200, verbose_name='Ссылка'),
        ),
    ]
