# Generated by Django 4.2.2 on 2023-06-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_avito', '0003_arendacar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='arendacar',
            name='taxopark',
            field=models.CharField(default='', max_length=200, verbose_name='название компании'),
        ),
    ]
