# Generated by Django 4.2.2 on 2023-06-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_avito', '0004_arendacar_taxopark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arendacar',
            options={'verbose_name': 'Список аренды авто Avito', 'verbose_name_plural': 'Список аренды авто Avito'},
        ),
        migrations.AddField(
            model_name='arendacar',
            name='description',
            field=models.TextField(default='', verbose_name='Описание объявления'),
        ),
    ]
