# Generated by Django 4.2.2 on 2023-06-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_avito', '0005_alter_arendacar_options_arendacar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='arendacar',
            name='schedule',
            field=models.CharField(default='не указан', max_length=20, verbose_name='Граффик'),
        ),
    ]
