# Generated by Django 4.2.2 on 2023-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_avito', '0006_arendacar_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='arendacar',
            name='placement_date',
            field=models.CharField(default='', max_length=30, verbose_name='дата размещения'),
        ),
    ]
