# Generated by Django 4.2.2 on 2023-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_avito', '0007_arendacar_placement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arendacar',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='arendacar',
            name='model',
        ),
        migrations.AddField(
            model_name='arendacar',
            name='cars',
            field=models.CharField(default='', max_length=500, verbose_name='Марка машины'),
        ),
    ]
