# Generated by Django 4.2.2 on 2023-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20, verbose_name='Марка машины')),
                ('model', models.CharField(max_length=20, verbose_name='Модель машины')),
                ('average_price', models.IntegerField(default=0, verbose_name='Средняя цена')),
            ],
            options={
                'verbose_name': 'список',
                'verbose_name_plural': 'Список ТС на AVITO',
            },
        ),
    ]
