# Generated by Django 4.2.2 on 2023-06-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'список', 'verbose_name_plural': 'Отчет по ценам на аренду авто'},
        ),
    ]
