# Generated by Django 4.2.2 on 2023-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_from',
            field=models.IntegerField(default=0, verbose_name='Пробег от: '),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_to',
            field=models.IntegerField(default=500000, verbose_name='Пробег до:'),
        ),
        migrations.AddField(
            model_name='car',
            name='year_from',
            field=models.IntegerField(default=2020, verbose_name='С какого года'),
        ),
        migrations.AddField(
            model_name='car',
            name='year_to',
            field=models.IntegerField(default=2023, verbose_name='По какой год'),
        ),
    ]
