# Generated by Django 4.2.2 on 2023-06-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_mileage_remove_car_price_remove_car_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=20, verbose_name='Модель машины'),
        ),
    ]
