# Generated by Django 4.2.2 on 2023-06-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины для парсинга'},
        ),
        migrations.AddField(
            model_name='car',
            name='activ_parsing',
            field=models.BooleanField(default=True, verbose_name='Активно/Неактивно'),
        ),
    ]
