# Generated by Django 4.2.2 on 2023-06-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_options_car_activ_parsing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Поиск подробных ТС на Auto.ru'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='year_to',
        ),
        migrations.AlterField(
            model_name='car',
            name='activ_parsing',
            field=models.BooleanField(default=True, verbose_name='Активно/ Не активно'),
        ),
    ]
