# Generated by Django 4.2.2 on 2023-06-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_options_remove_car_year_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='activ_parsing',
        ),
    ]
