# Generated by Django 4.2.2 on 2023-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_activ_parsing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage_to',
            field=models.IntegerField(default=1000000, verbose_name='Пробег до:'),
        ),
    ]
