# Generated by Django 4.2.2 on 2023-06-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_mileage_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage_from',
            field=models.IntegerField(default=10000, verbose_name='Пробег от: '),
        ),
    ]
