# Generated by Django 4.2.2 on 2023-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_auto_avito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlistavito',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
