url = "https://www.avito.ru/moskva_i_mo/avtomobili/"
url_for_jac = "https://www.avito.ru/moskva_i_mo/avtomobili/jac/j7/i-ASgCAQICA0Dgtg0UwJgo4rYNFPDcPeq2DRTe3D0?cd=1"
url_for_kia_k5 = "https://www.avito.ru/moskva_i_mo/avtomobili/kia/k5-ASgCAQICAkDgtg0Uypgo4rYNFLqoKA?cd=1"
prefix = "-ASgCAQICAkDgtg0Uypgo4rYNFMquKA?cd=1&p="

kia_rio = f"{url}kia/rio{prefix}"
chery_tigo_4 =f"{url}chery/tiggo_4-ASgCAQICAkDgtg0U9Jco4rYNFKjzMg ?cd=1"
jac_j_7 =          f"{url}jac/j7/i-ASgCAQICA0Dgtg0U wJgo4rYNFPDcPeq2DRTe3D0 ?cd=1"
h_s =        f"{url}hyundai/sonata-ASgCAQICAkDgtg0U opsx4rYNFOabMQ ?cd=1"
kia_ceed =         f"{url}kia/ceed-ASgCAQICAkDgtg0U ypgo4rYNFJShKA ?cd=1"
kia_cerato =     f"{url}kia/cerato-ASgCAQICAkDgtg0U ypgo4rYNFKqhKA ?cd=1"
kia_k_5 =            f"{url}kia/k5-ASgCAQICAkDgtg0U ypgo4rYNFLqoKA ?cd=1"
kia_optima   =   f"{url}kia/optima-ASgCAQICAkDgtg0U ypgo4rYNFJisKA ?cd=1"
nissan_qua = f"{url}nissan/qashqai-ASgCAQICAkDgtg0U ~pgo4rYNFNqtKA ?cd=1"
skoda_octav = f"{url}skoda/octavia-ASgCAQICAkDgtg0U npko4rYNFISsKA ?cd=1"
skoda_rapid =   f"{url}skoda/rapid-ASgCAQICAkDgtg0U npko4rYNFJSuKA ?cd=1"
toyota_camry = f"{url}toyota/camry-ASgCAQICAkDgtg0U tJko4rYNFNSgKA ?cd=1"
volkswage = f"{url}volkswagen/polo-ASgCAQICAkDgtg0U uJko4rYNFIitKA ?cd=1"